# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CLOUDERA_USER": "requests.ipynb",
         "CLOUDERA_PASS": "requests.ipynb",
         "CLOUDERA_CLUSTER": "requests.ipynb",
         "CLOUDERA_NIFI_REST": "requests.ipynb",
         "NIFI_API_URL": "requests.ipynb",
         "NIFI_API_PROCESSORS": "requests.ipynb",
         "NIFI_API_CONNECTIONS": "requests.ipynb",
         "NIFI_API_FLOWFILE_QUEUES": "requests.ipynb",
         "CLOUDERA_CREDENTIALS": "requests.ipynb",
         "NIFI_OBJECT_IDS": "01_endpoints.ipynb",
         "SOURCE_TO_RAW_IDS": "01_endpoints.ipynb",
         "Processor": "05_rest.ipynb",
         "Connection": "05_rest.ipynb",
         "Flowfile": "05_rest.ipynb",
         "custom_response": "20_tools.ipynb",
         "get_processor": "requests.ipynb",
         "update_processor": "requests.ipynb",
         "get_connection": "requests.ipynb",
         "list_flowfile_queues": "requests.ipynb",
         "get_flowfile_queues": "requests.ipynb"}

modules = ["endpoints.py",
           "processors.py",
           "connections.py",
           "flowfile_queues.py",
           "rest.py",
           "dataflow.py",
           "tools.py",
           "requests.py"]

doc_url = "https://kikejimenez.github.io/nifi_api/"

git_url = "https://github.com/kikejimenez/nifi_api/tree/main/"

def custom_doc_links(name): return None
