# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CLOUDERA_USER": "requests.ipynb",
         "CLOUDERA_PASS": "requests.ipynb",
         "CLOUDERA_CLUSTER": "requests.ipynb",
         "CLOUDERA_NIFI_REST": "requests.ipynb",
         "NIFI_API_URL": "requests.ipynb",
         "NIFI_API_PROCESSORS": "requests.ipynb",
         "NIFI_API_CONNECTIONS": "requests.ipynb",
         "NIFI_API_FLOWFILE_QUEUES": "requests.ipynb",
         "CLOUDERA_CREDENTIALS": "requests.ipynb",
         "Processor": "02_processors.ipynb",
         "Connection": "03_connections.ipynb",
         "FlowfileQueues": "03_flowfile_queues.ipynb",
         "get_processor": "requests.ipynb",
         "update_processor": "requests.ipynb",
         "get_connection": "requests.ipynb",
         "list_flowfile_queues": "requests.ipynb",
         "get_flowfile_queues": "requests.ipynb"}

modules = ["endpoints.py",
           "processors.py",
           "connections.py",
           "flowfile_queues.py",
           "requests.py"]

doc_url = "https://kikejimenez.github.io/nifi_api/"

git_url = "https://github.com/kikejimenez/nifi_api/tree/main/"

def custom_doc_links(name): return None
