# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://kikejimenez.github.io/nifi_api/"

git_url = "https://github.com/kikejimenez/nifi_api/tree/main/"

def custom_doc_links(name): return None
