# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_flowfile_queues.ipynb (unless otherwise specified).

__all__ = ['Flowfile']

# Cell
import requests
from .endpoints import *
import json

# Cell
class Flowfile:

    nifi_api = NIFI_API_FLOWFILE_QUEUES

    @staticmethod
    def custom_response(res):
        try:
            return json.loads(res.text), res
        except:
            return "No JSON available", res

    @classmethod
    def list_queues(connection_id):
        url = nifi_api + f"{connection_id}/listing-requests"
        res = requests.post(url, auth=CLOUDERA_CREDENTIALS)
        return custom_response(res)
