# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_tools.ipynb (unless otherwise specified).

__all__ = ['custom_response', 'is_valid_csv']

# Cell
import json

# Cell
def custom_response(res):
    try:
        return json.loads(res.text), res
    except:
        return "No JSON available", res

# Cell
def is_valid_csv(file):
    valid_names = ['agents', 'calls', 'summary', 'skills', 'teams', 'campaings']
    filename = file.split('/')[-1].split('.')[0]
    return any(name in filename  for name in valid_names)