# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/20_tools.ipynb (unless otherwise specified).

__all__ = ['custom_response']

# Cell
import json

# Cell
def custom_response(res):
    try:
        return json.loads(res.text), res
    except:
        return "No JSON available", res