# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/09_tools.ipynb (unless otherwise specified).

__all__ = ['custom_response', 'is_valid_csv', 'get_valid_uuids_in_connector']

# Cell
import json

# Cell

def custom_response(res):
    try:
        return json.loads(res.text), res
    except:
        return "No JSON available", res

# Cell
def is_valid_csv(file):
    """ A valid file is a filename is csv file that with sufix in a given
    set of valid names
    """
    valid_names = ['agents', 'calls', 'summary', 'skills', 'teams', 'campaings']

    filename = file.split('/')[-1].split('.')
    if len(filename) == 1:
        return False

    fname, ext = filename

    return any(
        vname in fname for vname in valid_names) and ext.lower() == 'csv'

# Cell


def get_valid_uuids_in_connector(list_queues):
    """ Gets a list of valid UUIDs from the list of queues
    """
    flowfile_summaries = list_queues['flowFileSummaries']
    valid_uuids = [
        ff['uuid'] for ff in flowfile_summaries if is_valid_csv(ff['filename'])
    ]
    return valid_uuids